@HOST=http://localhost:3000

POST {{HOST}}/api/products
Content-Type: application/json

{
  "name": "Guarnición 14x100 cm",
  "model": "Guarnición 14x100 cm",
  "colors": [],
  "description": "La guarnición prefabricada es un elemento de concreto con dimensiones de 100 cm de largo, 27 cm de alto y peso aproximado de 80 kg. Fabricada con cemento, agua, arena y aditivos, se utiliza como delimitador entre calzada y banqueta, así como tope-llanta en estacionamientos. Sus curvas precisas no requieren cimbra ni colado, lo que reduce costos y tiempo de obra. Su acabado liso mejora la estética y permite recuperación de piezas para mantenimiento. Se instala sobre terreno compactado con mortero común, cuidando niveles con regla o hilo, y se deja reposar 48 horas antes de rellenar. Ideal para tráfico rodado por su resistencia y facilidad de colocación.",
  "category": "Guarniciones",
  "technicalData": "PDFs DESCARGABLE",
  "image": "/assets/images/categorias/Guarniciones.png"
}

###
GET {{HOST}}/api/products

###
PATCH {{HOST}}/api/products/687759bbbc3859fa3ad67425
Content-Type: application/json

{
  "name": "Teja Aranjuez",
  "price": 120,
  "colors": ["red", "blue", "green", "yellow"],
  "description": "Teja Aranjuez Description Updated",
  "category": "Tejas",
  "image": "/assets/images/categorias/Placeholder Image.png"
}

###
DELETE {{HOST}}/api/products/6877512f21aae1f6a37447a1
 
 ###
GET {{HOST}}/api/products/tejas


###
GET {{HOST}}/api/products/categories